# docker-compose.prod.yml
# Este archivo está optimizado para producción y SOLO gestiona el backend y las bases de datos.
# El frontend se despliega directamente en el Nginx del host.

services:
  backend:
    image: ghcr.io/the-matius/alamesa/alamesa-backend:production
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      POSTGRES_HOST: postgresql
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      ENVIRONMENT: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - mongodb
      - postgresql
    networks:
      - alamesa-network

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - alamesa-network

  postgresql:
    image: postgres:13
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - alamesa-network

volumes:
  mongodb_data:
  postgresql_data:

networks:
  alamesa-network:
    driver: bridge